name: Node.js Test Runner

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: chathaven
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpassword
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u testuser -ptestpassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name:  Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: src/package-lock.json

      - name:  Install deps
        run: cd src && npm install

      - name:  Run DB Schema (like your XAMPP background does)
        run: |
          sudo apt-get update && sudo apt-get install -y mysql-client
          echo "Loading schema..."
          mysql -h 127.0.0.1 -u testuser -ptestpassword chathaven < src/database/schema.sql

      - name:  Run Jest Tests (you handle ports, sockets, DB in test files)
        env:
          DB_HOST: 127.0.0.1
          DB_USER: testuser
          DB_PASSWORD: testpassword
          DB_DATABASE: chathaven
        run: |
          cd src
          npm test -- --ci --runInBand --detectOpenHandles


  deploy:
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: src/public
        token: ${{ secrets.GH_TOKEN }}
